[package]
name = "compression"
version = "0.1.0"
description = "Compression and decompression algorithms with support for DEFLATE, GZIP, Brotli."
repository = "https://github.com/edjcase/motoko_compression"
license = "MIT"
keywords = ["compression", "decompression", "deflate", "gzip"]

[dependencies]
base = "0.14.9"
itertools = "0.2.2"
circular-buffer = "0.0.1"
bitbuffer = "1.2.0"
buffer-deque = "0.1.0"
test = "2.1.1"

[dev-dependencies]
test = "2.1.1"
