name: Makefile CI

on:
    [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                node-version: 14

            - name: Installing DFX
              run: DFX_VERSION=0.14.0 sh -ci "$(curl -fsSL https://internetcomputer.org/install.sh)"
           
            - name: Install moc version manager
              run: | 
                  npm  --yes -g i mocv
                  mocv use 0.9.1
                  export DFX_MOC_PATH=$(mocv bin current)/moc

            - name: install mops
              run: |
                  npm --yes -g i ic-mops@0.8.3
                  mops i

            - name: Detect Warnings
              run: make no-warn

            - name: run actor tests
              run: make actor-tests
