name: Makefile CI

on:
    [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                node-version: 14
            - uses: aviate-labs/setup-dfx@v0.2.3
              with:
                vessel-version: 0.6.3
                dfx-version: 0.13.1

            - name: install mops
              run: |
                  npm --yes -g i ic-mops@0.8.3
                  mops i
                  mops sources
            
            - name: install zx
              run: npm i -g zx

            - name: Detect Warnings
              run: make no-warn

            - name: run actor tests
              run: zx actor-tests.mjs
